### ISSUE TITLE
Master Branch contains UI code

### ISSUE THREAD

**Issue by DanMeakin** [DanMeakin/P7-Project#1]
Hey guys,

We have some problems with the codebase right now, as the master branch contains UI code which is not compiling.

I plan this evening to remove the UI code from the master branch. Obviously historic copies of the files will be retained, so I suggest that if there is anything new in master which isn't in the UI branch you can get the code from the historic copy and insert it as required.

Also, for some reason we have both a GUI branch and a UI branch. As I'm not working on the UI I don't want to touch these, but can we remove whichever branch is not required? 

Thanks! :+1:

**Comment by Hyllested** [comment]
Sorry about that, was not aware that I had done that. But the reason I made
a new branch is that after it has been merged with the master branch at
some point, I can not access it anymore.
Den 05/12/2015 19.00 skrev "Dan Meakin" notifications@github.com:

**Comment by DanMeakin** [comment]
Hey Helle,
No problem. I didn't realise it wasn't accessible. Did you try doing a checkout into the GUI (?) branch, or try pulling it? If there is a branch which is to be deleted, we can do this. Do you know if it's UI or GUI you and Janus are working on? I can (probably) delete the one which isn't needed.
Thanks!

**Comment by Hyllested** [comment]
Yes, but none worked. We are working on ui. So everything in gui is okay to
delete.
Den 05/12/2015 19.16 skrev "Dan Meakin" notifications@github.com:

**Comment by DanMeakin** [comment]
Ok that's the GUI branch gone now.
